# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/mahi.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_1_0/design_1_zynq_ultra_ps_e_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_1_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_1_0} -quiet] -quiet

# XDC: c:/Users/mahim/project_2/project_2.gen/sources_1/bd/design_1/design_1_ooc.xdc
